server:
  port: 9090
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

swagger.url: http://localhost:9090/swagger.json

spring:
  application:
    name: swaggerConvertWord

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.31:3306/rtls?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.cmcc.rtls.model
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
